backend:
  name: git-gateway
  branch: main
  identity_url: "https://jayedinsight.me/.netlify/identity"
  gateway_url: "https://jayedinsight.me/.netlify/git"

media_folder: "images/uploads"

collections:
  - name: "business"
    label: "Business Articles"
    folder: "_business"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Cover Image", name: "image", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "cricket"
    label: "Cricket Articles"
    folder: "_cricket"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Cover Image", name: "image", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
